export const MovieNameAndPoster = {
  "Fantastic Beasts: The Crimes of Grindelwald": `img/fantastic-beasts-the-crimes-of-grindelwald.jpg`,
  "Bohemian Rhapsody": `img/bohemian-rhapsody.jpg`,
  "Macbeth": `img/macbeth.jpg`,
  "Aviator": `img/aviator.jpg`,
  "We need to talk about Kevin": `img/we-need-to-talk-about-kevin.jpg`,
  "What We Do in the Shadows": `img/what-we-do-in-the-shadows.jpg`,
  "Revenant": `img/revenant.jpg`,
  "Johnny English": `img/johnny-english.jpg`,
  "Shutter Island": `img/shutter-island.jpg`,
  "Pulp Fiction": `img/pulp-fiction.jpg`,
  "No Country for Old Men": `img/no-country-for-old-men.jpg`,
  "Snatch": `img/snatch.jpg`,
  "Moonrise Kingdom": `img/moonrise-kingdom.jpg`,
  "Seven Years in Tibet": `img/seven-years-in-tibet.jpg`,
  "Midnight Special": `img/midnight-special.jpg`,
  "War of the Worlds": `img/war-of-the-worlds.jpg`,
  "Dardjeeling Limited": `img/dardjeeling-limited.jpg`,
  "Orlando": `img/orlando.jpg`,
  "Mindhunter": `img/mindhunter.jpg`
};
